version: "3.9"
services:
  protect-pg:
    image: postgres:14
    volumes:
      - ./mnt/pg-init:/docker-entrypoint-initdb.d
      - ./mnt/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: F3zCcZS5yN5UZYkaCx3P
      POSTGRES_USER: unifi-core
      POSTGRES_DB: unifi-core
    restart: always
#    ports:
#      - "4432:5432"
  protect:
    image: iamtopcat/unifi-protect-arm64:3.2.12-3.0.22
    privileged: true
#    network_mode: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./mnt/srv:/srv
      - ./mnt/data:/data
      - ./mnt/persistent:/persistent
      - ./mnt/.pgpass:/root/.pgpass
      - ./mnt/unifi-core.yaml:/data/unifi-core/config/overrides/production.yaml
      - ./mnt/ulp-go.yaml:/etc/ulp-go/config.props
      - ./mnt/ulp-go.pg.sh:/data/ulp-go.pg.sh
      - ./mnt/unifi-protect.yaml:/etc/unifi-protect/config.json
      - /etc/resolv.conf:/run/systemd/resolve/resolv.conf
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      STORAGE_DISK: /data
    restart: always
